apiVersion: v1
kind: Service
metadata:
  name: tops2-frontend
  labels:
    app: tops2-frontend
spec:
  type: LoadBalancer
  selector:
    app: tops2-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
